<a href="https://colab.research.google.com/github/jarring824/F25-MAT-1630/blob/main/mat_1630_10_6_25_ipynb_exerise's.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# list comprehension **approach**

In [1]:
f_list = [4*n**3 - 1 for n in range(7)]
print(f_list)

[-1, 3, 31, 107, 255, 499, 863]


# Numpy approach

In [2]:
import numpy as np

x = np.arange(7)
f_np = 4*x**3 - 1
print(f_np)


[ -1   3  31 107 255 499 863]


# list comprehension part 2

In [3]:
S = [(m, n) for m in range(4) for n in range(4)]
print(S)
print(len(S))

[(0, 0), (0, 1), (0, 2), (0, 3), (1, 0), (1, 1), (1, 2), (1, 3), (2, 0), (2, 1), (2, 2), (2, 3), (3, 0), (3, 1), (3, 2), (3, 3)]
16


# numpy arrays practice

In [4]:
import numpy as np

L = [2, 4, 6, 8, 10]
a = np.array(L)
print("a =", a)
print("a**2 =", a**2)
print("cumsum =", a.cumsum())
print("sin(a) =", np.sin(a))
x = np.linspace(0, 1, 9)
print("linspace =", x)
M = np.array([
    [1, 2, 3],
    [0, 0, 0],
    [7, 5, 4]
])
print("M =\n", M)
print("M[0,1] =", M[0,1])      # first row, second column
print("M[:,2] =", M[:,2])      # third column
print("M[1:,:] =\n", M[1:,:])  # first row as 2D slice
vstacked = np.stack((a, a**2))
hstacked = np.hstack((a, a**2))

print("Vertical stack:\n", vstacked)
print("Horizontal stack:\n", hstacked)

a = [ 2  4  6  8 10]
a**2 = [  4  16  36  64 100]
cumsum = [ 2  6 12 20 30]
sin(a) = [ 0.90929743 -0.7568025  -0.2794155   0.98935825 -0.54402111]
linspace = [0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875 1.   ]
M =
 [[1 2 3]
 [0 0 0]
 [7 5 4]]
M[0,1] = 2
M[:,2] = [3 0 4]
M[1:,:] =
 [[0 0 0]
 [7 5 4]]
Vertical stack:
 [[  2   4   6   8  10]
 [  4  16  36  64 100]]
Horizontal stack:
 [  2   4   6   8  10   4  16  36  64 100]
